import { Inter } from "next/font/google";
import "../styles/main.scss";
import { Provider } from "react-redux";
import { projectName } from "@/theme/theme-config";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Online Shop App",
  description: "Generated by create next app",
};

axios.defaults.baseURL = process.env.NEXT_PUBLIC_BASE_URL;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{projectName}</title>
        <meta name="description" content="online Shop App" />
      </head>
      <body className={inter.className}>
        <Provider> {children}</Provider>
      </body>
    </html>
  );
}
